#   Reference documentation for AWS CodeDeploy appspec.yml file:
#
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/application-revisions-appspec-file.html
#   http://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
files:
  - source: .
    destination: /srv/arteria
hooks:
  BeforeInstall:
    - location: scripts/prepare.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
      runas: ubuntu
