version: '3'

services:
  stackstorm:
    image: stackstorm/stackstorm:${ST2_VERSION_TAG:-latest}
    container_name: stackstorm
    env_file:
      - conf/stackstorm.env
      - conf/mongo.env
      - conf/rabbitmq.env
      - conf/postgres.env
      - conf/redis.env
    ports:
      - "443:443"
    networks:
      - public
      - private
    volumes:
      - ./packs.dev:/opt/stackstorm/packs.dev
      - stackstorm-log-volume:/var/log
      - ./runtime/entrypoint.d:/st2-docker/entrypoint.d
      - ./runtime/st2.d:/st2-docker/st2.d
      - ./conf/stackstorm.env:/st2-docker/env
    dns_search: .


### External Services

  mongo:
    image: mongo:3.4
    container_name: mongo
    env_file:
      - conf/mongo.env
    networks:
      - private
    volumes:
      - mongo-volume:/data/db
    dns_search: .
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - conf/rabbitmq.env
    networks:
      - private
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq
    dns_search: .
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - conf/postgres.env
    networks:
      - private
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    dns_search: .
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - conf/redis.env
    networks:
      - private
    volumes:
      - redis-volume:/data
    dns_search: .

### Additional services for Arteria testing

  runfolder:
    build: ./docker-runfolder
    image: local/runfolder:latest
    container_name: runfolder_ws
    ports:
      - "7010:80"
    networks:
      - public

  bcl2fastq:
    build: ./docker-bcl2fastq
    image: local/bcl2fastq:latest
    container_name: bcl2fastq_ws
    ports:
      - "7020:80"
    networks:
      - public

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "7000:80"
    networks:
      - public
    volumes:
      - ./docker-nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker-nginx:/usr/share/nginx/html:ro
    depends_on:
      - "bcl2fastq"
      - "runfolder"


volumes:
  mongo-volume:
  postgres-volume:
  rabbitmq-volume:
  redis-volume:
  stackstorm-log-volume:

networks:
  public:
    driver: bridge
  private:
    driver: bridge
